name: Code Review Workflow

on:
  pull_request:
    branches: [main]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (code style check)
        run: |
          npx eslint . || echo "Linting completed with warnings"

      - name: Run CodeQL Analysis (security scan)
        uses: github/codeql-action/analyze@v3
        with:
          category: 'security'
