name: Documentation Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate documentation folder
        run: |
          mkdir -p docs
           echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Heavens Above Docs</title></head><body><h1>Welcome to Heavens Above</h1><p>This is the project documentation home page.</p></body></html>" > docs/index.html
           touch docs/.nojekyll
           echo "Documentation folder prepared."



      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
